module("EventType", package.seeall)

GAME_TEST_PRINT = THSTG.UIDUtil.getEventUID()
GAME_REPLACE_SCENE = THSTG.UIDUtil.getEventUID()
--开始菜单项
STARTITEM_SELECTDIFF_SELECT = THSTG.UIDUtil.getEventUID()
STARTITEM_SELECTDIFF_CANCEL = THSTG.UIDUtil.getEventUID()

STARTITEM_SELECTROLE_SELECT = THSTG.UIDUtil.getEventUID()
STARTITEM_SELECTROLE_CANCEL = THSTG.UIDUtil.getEventUID()