require "Configs.Types.EventType"
require "Configs.Types.ModuleType"
require "Configs.Types.ResType"
require "Configs.Types.FontType"
require "Configs.Types.UIType"
require "Configs.Types.TexType"
require "Configs.Types.SceneType"