module("EventType", package.seeall)

--开始菜单项
STARTITEM_SELECTDIFF_SELECT = UIDUtil.getEventUID()
STARTITEM_SELECTDIFF_CANCEL = UIDUtil.getEventUID()
STARTITEM_SELECTROLE_SELECT = UIDUtil.getEventUID()
STARTITEM_SELECTROLE_CANCEL = UIDUtil.getEventUID()


--加载模块
LOADING_EXECUTE = UIDUtil.getEventUID()
LOADING_BUSY = UIDUtil.getEventUID()


--舞台模块
STAGE_ENTER = UIDUtil.getEventUID()
