require "Scripts.Game.Definition.Type.EventType"
require "Scripts.Game.Definition.Type.ModuleType"
require "Scripts.Game.Definition.Type.ResType"
require "Scripts.Game.Definition.Type.FontType"
require "Scripts.Game.Definition.Type.UIType"
require "Scripts.Game.Definition.Type.TexType"
require "Scripts.Game.Definition.Type.SceneType"
require "Scripts.Game.Definition.Type.GUIType"