require "Scripts.Context.Handler.ConfigReaders.MainMenuConfig"
require "Scripts.Context.Handler.ConfigReaders.SelectionConfig"
require "Scripts.Context.Handler.ConfigReaders.ConstConfig"
require "Scripts.Context.Handler.ConfigReaders.SheetConfig"
require "Scripts.Context.Handler.ConfigReaders.ShaderConfig"
require "Scripts.Context.Handler.ConfigReaders.SoundConfig"
require "Scripts.Context.Handler.ConfigReaders.SkeletonConfig"

require "Scripts.Context.Handler.ConfigReaders.BossConfig"
require "Scripts.Context.Handler.ConfigReaders.PropConfig"
require "Scripts.Context.Handler.ConfigReaders.EnemyBulletConfig"
require "Scripts.Context.Handler.ConfigReaders.PlayerBulletConfig"
require "Scripts.Context.Handler.ConfigReaders.BatmanConfig"
require "Scripts.Context.Handler.ConfigReaders.PlayerConfig"
require "Scripts.Context.Handler.ConfigReaders.StageConfig"

